### ISSUE TITLE
Not possible to compile with Ecto 3.6.0

### ISSUE THREAD

**Issue by oliver-kriska** [danielberkompas/cloak_ecto#20]
Hi,

when we wanted to upgrade Ecto to 3.6.0 ([diff](https://diff.hex.pm/diff/ecto/3.5.4..3.6.0), [changelog](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#v360-2021-04-03) but after upgrade it's not possible to compile our projects. 

There is error:
```
= Compilation error in file lib/our_app/models/model.ex ==
** (ArgumentError) argument error
    (stdlib 3.14) :ets.lookup(OurApp.Vault.Config, :config)
    (cloak 1.0.3) lib/cloak/vault.ex:285: Cloak.Vault.read_config/1
    lib/cloak/vault.ex:266: OurApp.Vault.json_library/0
    lib/cloak_ecto/types/map.ex:60: OurApp.Vault.Map.before_encrypt/1
    lib/cloak_ecto/type.ex:36: OurApp.Vault.Map.dump/1
    (ecto 3.6.0) lib/ecto/schema.ex:2091: Ecto.Schema.validate_default!/2
    (ecto 3.6.0) lib/ecto/schema.ex:1830: Ecto.Schema.__field__/4
    lib/our_app/models/model.ex:19: (module)
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```
Looks like it want to load configuration from ETS which is not available at compile time. 

We figured out that default value for field is creating this issue.
This works:
```
field :responses, OurApp.Vault.Map
```
This doesn't work
```
field :responses, OurApp.Vault.Map, default: %{}
```

Config:

```
defmodule OurApp.Vault do
  use Cloak.Vault, otp_app: :our_app

  @impl GenServer
  def init(config) do
    config =
      Keyword.put(config, :ciphers,
        default: {Cloak.Ciphers.AES.GCM, tag: "AES.GCM.V1", key: decode_env!("CLOAK_SECRET")}
      )

    {:ok, config}
  end

  defp decode_env!(var), do: System.get_env(var) |> decode!()

  defp decode!(nil), do: Application.get_all_env(:our_app)[OurApp.Vault][:key] |> Base.decode64!()
  defp decode!(var), do: Base.decode64!(var)
end

```
Any suggestions to fix this?

**Comment by caciatori** [comment]
We are having the same problem in our schemas for default values

**Comment by nickdichev** [comment]
I'm running into this as well! Some guidance would be appreciated :)

**Comment by danielberkompas** [comment]
@oliver-kriska @nickdichev It looks like this is happening because Ecto is now calling `Ecto.Type.dump` on the default value at compile time.  It didn't before. 

I'm not sure what can be done here, since Cloak vaults are designed to be configured and run at _runtime_, not compile time. This Ecto change forces the vault to run at compile time, when its configuration may not be available. 

Is there a way for the Cloak.Ecto types to tell if they are being called at compile time? If so, perhaps we could just return `:ok` when `dump` is called at compile time.

**Comment by oliver-kriska** [comment]
yes, I think it's this part of upgrade:
https://diff.hex.pm/diff/ecto/3.5.4..3.6.0#37373710--2091

It calls dump, dump call cast and cast try to load configuration. Maybe we can check if ets is available. I tried this:

```
 def read_config(table_name) do
    if :undefined == :ets.info(table_name) do
      Cloak.InvalidConfig.exception("could not load configuration from ets")
      # ??????????
      []
    else
      case :ets.lookup(table_name, :config) do
        [{:config, config} | _] ->
          config

        _ ->
          :error
      end
    end
  end
```
But I got error 
```
** (ArgumentError) value [] is invalid for type Payout.Vault.MapList, can't set default
```
So I'm not sure what I have to return to get it right.  I think it try to load json library. So maybe we can load default values from config.exs or env.exs. Any suggestions?

**Comment by nickdichev** [comment]
Could the definition of `dump/1` in `type.ex` change? Right now the way it is written it will always try to read the ETS table created by the Cloak vault. However, couldn't it be changed to something like this:

```
def dump(value) do
  case cast(value) do
    [:ok, value} -> maybe_encrypt_value(value)
    _otherwise -> :error
  end
end

defp maybe_encrypt_value(value) do
  if vault_started?,
    do: encrypt_value(value),
    else: value
end

defp vault_started?() do
  not_nil? = &(not is_nil(&1))

  unquote(vault)
  |> Process.whereis()
  |> not_nil?.()
end

defp encrypt_value(value) do
  with value <- before_encrypt(value),
       {:ok, value} <- encrypt(value) do
  else
    _otherwise -> :error
  end
end
```

This way at compile time just the Cloak.Ecto.Type `cast/1` is called so we can correctly satisfy the call to `validate_default!/2`  at compile time. Only if the actual Cloak vault is started will we try to read the ets config and do the encryption.

@danielberkompas thoughts on this?

**Comment by nickdichev** [comment]
Yes, I think it's possible if there are children of the top-level application supervision tree that are started before the vault. Since the children of the supervision tree [start/shutdown](https://hexdocs.pm/elixir/1.12/Supervisor.html#module-start-and-shutdown) in sequential order if something is started before the vault, and it tries to `dump/1` something I suppose it would end up en-encrypted. No good.

I wonder if its possible to do something tricky with some sort of `__before_compile__`, `__after_compile__`, or `__on_definition__` hook. The [docs](https://hexdocs.pm/elixir/1.12/Module.html#module-on_definition-1) about `__on_definition__` mention something sort of curious:

```
Unlike other hooks, @on_definition will only invoke functions and never macros. This is to avoid @on_definition callbacks from redefining functions that have just been defined in favor of more explicit approaches.
```

Although I'm not sure what the more explicit approach it mentions is...

**Comment by oliver-kriska** [comment]
Hi, any news? Not sure if I can help with something.

**Comment by nickdichev** [comment]
Likewise would appreciate any update here. Being stuck on 3.6 is starting to cause issues with other packages which are starting to lock `~> 3.7`.

**Comment by josevalim** [comment]
Ecto master supports `:skip_default_validation` on `field` and I will backport it to v3.7 and release it shortly. I recommend updating the README of this project. :)

**Comment by nickdichev** [comment]
I opened a PR #32 to address this in the README. @danielberkompas I have a note in that PR for you to check out since things will not work for anyone on `3.7.2 >= ecto version >= 3.6.0`
